/**
 * GET /mcp/report.pdf — download the marketplace analysis report as PDF.
 * Filename: "August iHerb Shopee Analysis 2026.pdf".
 * Generated by scripts/_make_report_pdf.mjs from server/assets/report.html.
 */
export default defineEventHandler(async (event) => {
  const pdf = await useStorage('assets:server').getItemRaw('report.pdf')
  if (!pdf) {
    setResponseStatus(event, 404)
    return 'report pdf missing'
  }
  setHeader(event, 'Content-Type', 'application/pdf')
  setHeader(event, 'Content-Disposition', 'attachment; filename="August iHerb Shopee Analysis 2026.pdf"')
  setHeader(event, 'Cache-Control', 'public, max-age=300')
  return pdf
})
