export default defineEventHandler(() => {
  return {
    name: 'SKUMS API',
    version: '1.0.0',
    description: 'Global Product Database — manage products, brands, categories, and schemas.',
    auth: {
      methods: ['Bearer token', 'X-API-Key header', 'api_key query param'],
      note: 'Create API keys at Settings → API Keys in the SKUMS dashboard.',
    },
    endpoints: {
      products: {
        list: 'GET /api/v1/products',
        create: 'POST /api/v1/products',
        get: 'GET /api/v1/products/:id',
        identity: 'GET /api/v1/products/:id/identity',
        listings: 'GET /api/v1/products/:id/listings',
        skuAssignments: 'GET /api/v1/products/:id/sku-assignments',
        update: 'PUT /api/v1/products/:id',
        delete: 'DELETE /api/v1/products/:id',
      },
      listings: { list: 'GET /api/v1/listings' },
      imports: {
        list: 'GET /api/v1/imports',
        create: 'POST /api/v1/imports',
        get: 'GET /api/v1/imports/:id',
      },
      apps: {
        definitions: 'GET /api/v1/apps',
        workspaceApps: 'GET|POST /api/v1/workspace-apps',
        capabilitySources: 'GET|POST /api/v1/capability-sources',
      },
      events: {
        list: 'GET /api/v1/events',
        create: 'POST /api/v1/events',
      },
      agentProposals: {
        list: 'GET /api/v1/agent-proposals',
        create: 'POST /api/v1/agent-proposals',
        fromAttentionItem: 'POST /api/v1/agent-proposals/from-attention-item',
        dryRun: 'POST /api/v1/agent-proposals/:id/dry-run',
        execute: 'POST /api/v1/agent-proposals/:id/execute',
        decision: 'POST /api/v1/agent-proposals/:id/decision',
      },
      attentionItems: {
        list: 'GET /api/v1/attention-items',
        create: 'POST /api/v1/attention-items',
        resolve: 'POST /api/v1/attention-items/:id/resolve',
        createProposal: 'POST /api/v1/attention-items/:id/proposals',
      },
      pos: {
        catalog: 'GET /api/v1/pos/catalog',
        scan: 'POST /api/v1/pos/scan',
        createSale: 'POST /api/v1/pos/sales',
        inventoryEvents: 'POST /api/v1/pos/inventory-events',
      },
      tradeUnits: { assignSku: 'POST /api/v1/trade-units/:id/sku-assignments' },
      brands: { list: 'GET /api/v1/brands' },
      categories: { list: 'GET /api/v1/categories' },
      schemas: { list: 'GET /api/v1/schemas' },
      webhooks: { receive: 'POST /api/v1/webhooks/:path' },
      expiry: {
        batches: 'GET|POST /api/v1/expiry/batches',
        lifo: 'GET /api/v1/expiry/lifo',
        summary: 'GET /api/v1/expiry/summary',
        aliases: 'GET|POST /api/v1/expiry/aliases',
      },
      graphql: { endpoint: 'POST /api/graphql' },
    },
    openapi: '/api/v1/openapi',
    scopes: [
      'products:read',
      'products:write',
      'products:delete',
      'brands:read',
      'categories:read',
      'schemas:read',
      'api:read',
      'api:write',
      'apps:read',
      'apps:write',
      'events:read',
      'events:write',
      'agents:read',
      'agents:write',
      'pos:read',
      'pos:write',
    ],
  }
})
